name: Stale

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      # The 90 day stale policy for issues
      # Used for:
      # - Issues
      # - No issues marked as no-stale
      # - No PRs (-1)
      - name: 90 days stale issues
        uses: actions/stale@v7.0.0
        with:
          days-before-stale: 90
          days-before-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
          operations-per-run: 250
          remove-stale-when-updated: true
          stale-issue-label: "stale"
          exempt-issue-labels: "no-stale"
          stale-issue-message: >
            There hasn't been any activity on this issue recently. Issue will be marked
            as stale and closed after 7 days without any activity.
